language: c

arch:
 - amd64
 - ppc64le

env:
  global:
    - LUAROCKS=2.3.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit
    - LUA=luajit2.0
    - LUA=luajit2.1
jobs:
  exclude:
    - arch: ppc64le
      env: LUA=luajit2.0
    - arch: ppc64le
      env: LUA=luajit2.1

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted
  - luarocks install luacheck
  - luarocks remove luassert --force && luarocks make

script:
  - luacheck .
  - busted

branches:
  only:
    - master

notifications:
  webhooks:
    - http://hollow-mountain-1250.herokuapp.com/hubot/travis
  recipients:
    - engineers@olivinelabs.com
  email:
    on_success: always
    on_failure: always
